name: flutter_intro
description: "An introduction to Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flame: ^1.10.1
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.2
  flutter_deck: ^0.22.0
  intl: ^0.20.2
  video_player: ^2.8.2
  flame_audio: ^2.1.3
  go_router: ^16.2.4
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  nes_ui: ^0.26.0
  google_fonts: ^6.1.0
  logging: ^1.2.0
  http: ^1.1.2
  url_launcher: ^6.2.3
  auto_size_text: ^3.0.0
  lottie: ^3.3.2
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/videos/
    - assets/images/dash/
    - assets/images/enemies/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf
